Fix/Code Smells Removal
claimsforce-gmbh/flutter-segment pull request #93
Opened 2021-10-28 13:07 UTC by ariefwijaya

## Purpose
- Remove Code Smells and fix the linters to pass the analyzer

## Types of changes
- [X] Fix (non-breaking change which fixes an issue)

## How to Test
- run  `flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings`

## Environment
- [X] Development
- [X] Android
- [X] iOS

<details><summary> Attach your `flutter doctor -v` inside code block: </summary>
<p>

```
✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-ID)
    • Flutter version 2.5.2 at /Users/ittcel/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (8 days ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ittcel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64    • Android 9 (API 28) (emulator)
    • Chrome (web)                          • chrome        • web-javascript • Google Chrome 94.0.4606.71

• No issues found!
```

</p>
</details>

## Expected Results
- Pass the analyzer checks in CI
```
no-fatal-infos --no-fatal-warnings
Analyzing flutter-segment...                                    
No issues found! (ran in 7.3s)
```

## Screenshot
<img src="https://user-images.githubusercontent.com/24664153/139261375-433d1e50-8cc6-41dd-842b-5668df280a38.png" width="250" />

2021-10-29 23:43 UTC, danielgomezrico requested changes
It looks like this PR is the same as the previous one, can you check it out?

https://github.com/claimsforce-gmbh/flutter-segment/pull/91

2021-10-29 23:43 UTC, danielgomezrico commented on analysis_options.yaml
> +    implicit-casts: false
This is not fixing anything and may break the CI, can you check it please?

2021-10-29 23:43 UTC, danielgomezrico commented on android/build.gradle
> +
👀

2021-11-02 00:05 UTC, ariefwijaya commented on README.md
> +      moengageIntegrationEnabled: false,
Ah sorry I think this happened because I was created the branch from another branch not from master branch,

2021-11-02 00:05 UTC, ariefwijaya commented on README.md
> +      moengageIntegrationEnabled: false,
Ah sorry I think this happened because I was created the branch from another branch not from master branch,

2021-11-02 00:06 UTC, ariefwijaya commented
@danielgomezrico
 @MaiKay 
 
 Sorry, My bad. I will remove the MoEngage integration out of this PR or create another PR

2021-11-02 21:58 UTC, danielgomezrico commented
@ariefwijaya please do a rebase after you apply your changes, in this PR https://github.com/claimsforce-gmbh/flutter-segment/pull/95 the CI will be good to see if this does not break anything :)

2021-11-19 06:56 UTC, MaiKaY commented
> @ariefwijaya please do a rebase after you apply your changes, in this PR #95 the CI will be good to see if this does not break anything :)

@ariefwijaya just a friendly reminder :-D

2021-12-01 23:56 UTC, ariefwijaya commented on analysis_options.yaml
> +    implicit-casts: false
I have enabled this option because the analyzer throw this warning  
> "The value 'null' isn't supported by 'strong-mode'. 
> Try using one of the supported options: 'true' and 'false'.". 

We should remove or ignore "strong-mode" when there are no options. Since we have not used any options in strong-mode. I will remove the `strong-mode`.

@danielgomezrico

2021-12-01 23:56 UTC, ariefwijaya commented on android/build.gradle
> +
Sorry, my bad. I will remove any segment integration in this PR.

2021-12-01 23:56 UTC, ariefwijaya commented on android/build.gradle
> +
Removed

2021-12-02 00:01 UTC, ariefwijaya commented
Sorry for the late response, I was on vacation then.
Please kindly check again my PR and the replied conversations 
@danielgomezrico

2021-12-02 16:29 UTC, MaiKaY commented
@ariefwijaya thanks a lot for keeping this updated.
@danielgomezrico can we merge this?

2021-12-07 13:44 UTC, danielgomezrico approved these changes
Awesome job, thanks :)

2021-12-07 14:07 UTC, MaiKaY commented
> can you fix the related issues on linter before we merge it?

@ariefwijaya

2021-12-13 00:21 UTC, ariefwijaya commented
@MaiKaY Sorry, but I don't see any problems with my linter:
![image](https://user-images.githubusercontent.com/24664153/145735683-40d59236-c68c-42d2-8dec-03ac45b784f9.png)

2021-12-13 06:24 UTC, MaiKaY commented
@danielgomezrico may I ask you to check if your IDE "complaints" about the lint violation?

2021-12-15 11:46 UTC, danielgomezrico commented
@ariefwijaya can you try running `flutter analyze --no-pub --no-fatal-infos --no-fatal-warnings` on your terminal? can you see those there?

2021-12-17 06:21 UTC, merged